[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
prettyURLs = true
trailingSlash = true
buildDir = "./"
filePath = "/sitemap.xml"
changeFreq = "daily"
priority = 0.5
baseUrl = "https://vivaznewhaven.com"
package = "netlify-plugin-submit-sitemap"
